apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
commonLabels:
  app.kubernetes.io/name: prometheus
resources:
  - nifi-prometheus.yaml
images:
  - name: prom/prometheus
    newTag: v2.3.2
configMapGenerator:
  - name: prometheus-configuration
    files:
      - prometheus.yaml
