global:
  scrape_interval: 30s
scrape_configs:
  - job_name: 'nifi-metrics-endpoint'
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
            - default
    relabel_configs: 
      - source_labels: [__meta_kubernetes_pod_label_app]
        action: keep
        regex: 'nifi'
