apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
commonLabels:
  app.kubernetes.io/name: grafana
resources:
- deployment.yaml
- service.yaml
images:
- name: grafana/grafana
  newTag: 6.1.6
